genrule(
    name = "hello_world",
    out = "out.txt",
    srcs = ["source.txt"],
    cmd = "cat $(location //:hello_world) > $OUT && cat source.txt >> $OUT",
)

genrule(
    name = "hello_world_no_source",
    out = "out.txt",
    cmd = "cat $(location //:hello_world) && echo nosource > $OUT",
)
